version: 2

before:
  hooks:
    - make tidy

builds:
  - main: cmd/main.go
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^scripts:'